services:

  nestjs:
    image: rivasjf/backendheald:1.0.1
    container_name: nestjs_app
    ports:
      - "3000:3000"
    # restart: unless-stopped
    # depends_on:
    #   - db
    environment:
      DATABASE_URL: ${DATABASE_URL}
      TZ: America/Mexico_City
    # networks:
    #   - heald_net_network

#   db:
#     image: postgres:15-alpine
#     container_name: postgres_db_dev
#     ports:
#       - "5432:5432"
#     environment:
#       POSTGRES_USER: ${DB_USER}
#       POSTGRES_PASSWORD: ${DB_PASSWORD}
#       POSTGRES_DB: ${DB_NAME}
#     volumes:
#       - postgres_healdserver_dev:/var/lib/postgresql/data

# volumes:
#   postgres_healdserver_dev: